version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /opt/webhook:/opt/webhook
      - /opt/cicdtest/chat-messages-telegram:/opt/cicdtest/chat-messages-telegram 
    working_dir: /app
    ports:
      - "5000:5000"  # Map port 8080 on host to port 8000 in container
    command: ["python3", "webhook.py"]
