version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /opt/webhook:/opt/webhook
      - /opt/esphome-yaml-constructor:/opt/esphome-yaml-constructor
      - /opt/esphome-download-ota/esphome-yaml-constructor:/opt/esphome-download-ota/esphome-yaml-constructor
    working_dir: /app
    ports:
      - "5000:5000"
    command: ["python3", "webhook.py"]
